apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-runtime
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/efekaya-devops/idp-gitops
    targetRevision: main
    path: crossplane
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 8
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 3m
