{
 "title": "${{ values.name }}",
 "tags": [
  "idp-service",
  "frontend"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Requests / s",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(app_requests_total{job=\"${{ values.name }}\"}[1m])"
    }
   ]
  },
  {
   "title": "Active connections",
   "type": "stat",
   "gridPos": { "x": 12, "y": 0, "w": 6, "h": 8 },
   "targets": [
    {
     "expr": "nginx_connections_active{job=\"${{ values.name }}\"}"
    }
   ]
  },
  {
   "title": "Pod restarts",
   "type": "stat",
   "gridPos": { "x": 18, "y": 0, "w": 6, "h": 8 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"default\", pod=~\"${{ values.name }}.*\"})"
    }
   ]
  }
 ]
}