# shared setup for everything in this folder. the per-bucket files next to
# this one are generated by the portal, this bit is hand-maintained.
terraform {
  required_version = ">= 1.5"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = "eu-west-1"
  # nothing applies this in the demo - CI only runs fmt/validate. a real setup
  # would assume a role here and apply from a pipeline (atlantis, tfc, etc)
}
